name: FreeBSD-14.1 clang-18.1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - name: build with cmake in FreeBSD vm
      uses: vmactions/freebsd-vm@v1.1.5
      with:
        usesh: true
          pkg install -y cmake

        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=debug && # debug includes sanitizers
          cmake --build build  # includes tests by default, tests are run with env set to fail on sanitizers
