name: Ubuntu 24.04 (gcc-13, clang-18)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: build with cmake
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            export CC=gcc
            export CXX=g++
          elif [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake -S . -B build -DCMAKE_BUILD_TYPE=debug && # debug includes sanitizers
          cmake --build build  # includes tests by default, tests are run with env set to fail on sanitizers
